version: '3.3'

services:
    traefik:
        image: traefik:1.7-alpine
        networks:
            - traefik
        restart: always
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik.toml:/traefik.toml

networks:
    traefik:
        external: true
